### ISSUE TITLE
repeat crashes when removing and re-adding items to a list

### ISSUE THREAD

**Issue by taras** [PolymerLabs/lit-html#235]
I'm creating a [TodoMVC](https://github.com/microstates/todomvc/tree/skatejs/examples/skatejs) demo using [Microstates](https://github.com/cowboyd/microstates.js) + Skate.js + litHTML. 

I'm expecting to be able to add/remove items from a list but I'm getting `Uncaught (in promise) DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.` error.

```
repeat.js:70 Uncaught (in promise) DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.
    at Object (http://localhost:6006/static/preview.bundle.js:58408:23)
    at getValue (http://localhost:6006/static/preview.bundle.js:3814:17)
    at NodePart.setValue (http://localhost:6006/static/preview.bundle.js:3866:17)
    at TemplateInstance.update (http://localhost:6006/static/preview.bundle.js:4023:22)
    at render (http://localhost:6006/static/preview.bundle.js:3616:18)
    at render (http://localhost:6006/static/preview.bundle.js:58258:73)
    at HTMLElement.renderer (http://localhost:6006/static/preview.bundle.js:58199:90)
    at HTMLElement.renderer (http://localhost:6006/static/preview.bundle.js:41420:107)
    at HTMLElement.updated (http://localhost:6006/static/preview.bundle.js:41437:14)
    at http://localhost:6006/static/preview.bundle.js:41224:20
```

I created an image to show how to reproduce this error.
![repeat crashes](https://user-images.githubusercontent.com/74687/34320415-ebb04e68-e7c7-11e7-811b-71127730fdd1.gif)

I tried to [reproduce this issue with a test but the test passed](https://github.com/taras/lit-html/commit/e4f6bef81a06b880425849de230106778bf400fb).

If you'd like to reproduce this issue in my code base you can do the following:
1. git clone git@github.com:microstates/todomvc.git
2. git checkout skatejs
3. npm install
4. npm run storybook
5. go to `http://localhost:6006/`

Let me know what I can do to help track this down.

PS: litHTML is very interesting. I ❤️ how light it feels.

**Comment by bengfarrell** [comment]
thanks for reporting. I'm think I'm in the exact same boat. I also have a repeating list, and was also getting the same error. When I add items in a different order, I end up with either this error, the correct rendering, or an incomplete rendering. On that last one, I mean it doesn't render all of my items and doesn't throw an error. I think this condition leads to your error state somehow. If not all of the items are rendered, somewhere along the line a node tries to parent something where the parent doesn't exist.

Anyway I'm still working through it - but same problem: repeating list always works the first time, but on a re-render to the same container there's a weird state. I'll probably have to sit down with the lit-html source soon. Hopefully someone here can save us the trouble.

**Comment by bengfarrell** [comment]
Can't try code right now, but I was browsing the repeat source on my phone. It looks like there's a part cache (not tied to the instance) in repeat which could explain why it acts different on subsequent renders. There's a method to clear the cache....when I get back home, that's what I'm going to try

**Comment by bengfarrell** [comment]
Alright - last comment from me, because I think I'm good. When I use the latest from master and compile myself, I don't think the problem exists anymore (was using the latest from npm when I was running into trouble). Hopefully it's similar for you

**Comment by Lodin** [comment]
Isn't it a duplicate of #92?
I suppose the version in npm registry does not contain fix for this issue yet.

**Comment by taras** [comment]
I can confirm that master fixed my problem. I'll close this when master is published to npm.

Thank you!
